### ISSUE TITLE
Example in "Usage in code" doesn't work

### ISSUE THREAD

**Issue by mbongaerts** [emmagraham/metPropagate#1]
Dear all,

I tried the example below in /label_propagation/README.md, and I think the length of x_train and y_train should be 4 instead of 2 (?). Changing this makes the example work for me (and makes more sense given a 4x4 matrix). So maybe you could update this example.

Kind regards,

M. Bongaerts

**Comment by emmagraham** [comment]
Thank you for bringing this to our attention. Although this README file is from this repo: https://github.com/yamaguchiyuto/label_propagation, for clarity I have modified the example in label_propagation/README.md to take in a x_train and y_train array of length 4, as this is the correct usage.
