### ISSUE TITLE
Cannot find the graph file with edge weights

### ISSUE THREAD

**Issue by mbongaerts** [emmagraham/metPropagate#2]
Dear all,

In the repo I do see the graph file label_propagation/STRING_graph_file.txt. However, I see that this database is solely edges, and no weights are defined in this file. Is their a way to obtain these weights as well?

Kind regards,

M. Bongaerts

**Comment by emmagraham** [comment]
Apologies for the inconvenience. That file was included in error. The correct STRING file (including edges and weights) has now been uploaded [here](https://github.com/emmagraham/metPropagate/blob/master/integration/graph_files/STRING_graph_file_v11_functional_entire_db.txt.zip).
