### ISSUE TITLE
Amount of genes with node_ids does not match the amount of nodes in the graph database

### ISSUE THREAD

**Issue by mbongaerts** [emmagraham/metPropagate#3]
Dear all,

I loaded the graph file using the *read_graphfile* parser. It turns out that my graph is a matrix 18224x18224 matrix. In other words, it has 18224 nodes. Now, if I look at *STRING_graph_file_v11_gene_to_nodeid_mapping_functional_entire_db.txt* I see in total 19354 unique node IDs. This means that some nodes are missing in the graph file,  am I right?

For example, the gene ADSL seems to be absent here, which is a gene of interest for me.  Could you elaborate on this matter?
Thanks!

kind regards,

M. Bongaerts

**Comment by emmagraham** [comment]
As mentioned in [this](https://github.com/emmagraham/metPropagate/issues/2) issue, the correct graph file has been uploaded. There should be 19354 nodes in this graph file, as listed in _STRING_graph_file_v11_gene_to_nodeid_mapping_functional_entire_db.txt_. Thanks again for bringing this to our attention.
