### ISSUE TITLE
Intuition behind the ME score

### ISSUE THREAD

**Issue by mbongaerts** [emmagraham/metPropagate#4]
Dear all,

According to the paper you determine the ME score by calculating:
ME = -log2( p + 2) * Z = P(p) * Z

This score is not quite intuitive for me, which I will explain in a moment. First I plotted the p-value versus the first part of the equation, which I call P(p):
![image](https://user-images.githubusercontent.com/28530122/89026740-83686c00-d329-11ea-8938-89a30ae6ec2a.png)

So, the curve is monotonic decreasing, meaning in this case we are mostly interested in the values (y-axis) which are less negative (corresponds with lower p-values).  Now, by multiplying P(p) with your a maximum Z-scores (positive number) we get (for me) unexpected behavior. According to my logic,  by means of the Z multiplication you want to 'rescue' genes having a relative high p-value (thus low P(p) ) but still have a related metabolite with a high Z-score, therefore you (might) wanna raise their importance. Now, the opposite is happening, since you multiply a negative number with a positive number, making it even more negative thereby 'downscaling' its importance. Similarly, a gene which have a significant p-values but has a relative low maximum Z-score (lets say close to 0 ) gets even more importance! 

This score would for me makes more sense:
ME = -log2( p ) * Z 

I would be happy if you could elaborate on this more! Thank you!

Kind regards,

M. Bongaerts

**Comment by mbongaerts** [comment]
Looking at the code, it does makes sense:
https://github.com/emmagraham/metPropagate/blob/c5c0e60cefbd59d2f3729410d53c771003d6d198/integration/generate_labels_met_only.R#L14-L15

However, I think its wrongly stated in the paper.

**Comment by emmagraham** [comment]
Thank you for your comment. Indeed, the wording is unclear in our manuscript, and we will be filing a correction with the journal to make this more clear for future readers. The correct equation (using your terminology above) is: 
ME = P(x)*Z
where P(x) = -log2(unadjusted p-value) scaled between 0 and 1, and Z is the absolute value of the metabolite z-score of the largest magnitude (eg. 7.2 for a metabolite with z-score -7.2). For each patient, the ME score for all genes in HMDB are scaled between 0 and 1 and then used as input node labels for the label propagation step. Let me know if you have any further questions!

**Comment by mbongaerts** [comment]
> 
> 
> Thank you for your comment. Indeed, the wording is unclear in our manuscript, and we will be filing a correction with the journal to make this more clear for future readers. The correct equation (using your terminology above) is:
> ME = P(x)*Z
> where P(x) = -log2(unadjusted p-value) scaled between 0 and 1, and Z is the absolute value of the metabolite z-score of the largest magnitude (eg. 7.2 for a metabolite with z-score -7.2). For each patient, the ME score for all genes in HMDB are scaled between 0 and 1 and then used as input node labels for the label propagation step. Let me know if you have any further questions!

Thanks! This is indeed what is done when looking at the code (and makes sense). I recommend then to not only rewrite the text but also the equation. Something along the line:

ME = u(x) * Z
with u(x) =( P(x) - min(P(x) ) ) / ( max( P(x) ) - min( P(x) ) )
with P(x) = -log2( x + 2 )
x being the unadjusted p-value.
and Z being the maximum absolute Z-score. 

This I think is a complete description of what is done.
